### ISSUE TITLE
Add CodingSpecies

### ISSUE THREAD

**Issue by CodingSpecies** [Jaidevstudio/Unique-Github-Profiles#1]
![image](https://user-images.githubusercontent.com/70807500/131972052-cf42e215-e2e9-4f1b-a63a-d768a8c79dd9.png)

**Comment by CodingSpecies** [comment]
#2

**Comment by VasudevJaiswal** [comment]
Done ! Check the Repo

**Comment by CodingSpecies** [comment]
@VasudevJaiswal thank you, looks good.

**Comment by VasudevJaiswal** [comment]
Join for Discussion

https://discord.gg/ppHfsxu7

**Comment by VasudevJaiswal** [comment]
https://jdstudio.tk/pages/about.html
check you are become a maintainer our org

**Comment by Garryharryfarry** [comment]
@CodingSpecies 
Plz invite me as a owner plz
