### ISSUE TITLE
Implement changes from my PR

### ISSUE THREAD

**Issue by Panquesito7** [Jaidevstudio/Unique-Github-Profiles#14]
We could implement the changes from https://github.com/EddieHubCommunity/awesome-github-profiles/pull/652 to make the website better.
Let me know what do you think. Thanks.

**Comment by VasudevJaiswal** [comment]
Yes I do that

**Comment by VasudevJaiswal** [comment]
Plz do it

**Comment by VasudevJaiswal** [comment]
@Panquesito7 
1. You are our team member Plz do what to do

**Comment by CodingSpecies** [comment]
@Panquesito7 @VasudevJaiswal We need to try and change whatever we are doing to be different to Eddie Jaoude's organisation.
I will try to change some things too.
Thanks.

**Comment by VasudevJaiswal** [comment]
But I  need to bot auto msg yml for user interface because user can attract for the bot

**Comment by CodingSpecies** [comment]
@VasudevJaiswal I am trying to make it, but I am not sure how. We need a custom .yml file, and I need to configure the bot. Thanks.

**Comment by VasudevJaiswal** [comment]
@CodingSpecies 
We will try it no problem

**Comment by CodingSpecies** [comment]
I did make it, but I need to try it out.

**Comment by CodingSpecies** [comment]
The thing is, you have to be a new contributor, to make your first ever pr or issue

**Comment by VasudevJaiswal** [comment]
@CodingSpecies  @Panquesito7 
1. we are making  a github pages 
Which is real voting system ( page)   for Unique-github-profile  for users profile  
2. All user voting wise Rank table

**Comment by CodingSpecies** [comment]
this is the web page so far: https://jaidevstudio.github.io/Unique-Github-Profiles/

**Comment by VasudevJaiswal** [comment]
> this is the web page so far: https://jaidevstudio.github.io/Unique-Github-Profiles/

Points Voting system for user 
 points wise table
