### ISSUE TITLE
Motasim

### ISSUE THREAD

**Issue by motasimmakki** [Jaidevstudio/Unique-Github-Profiles#19]
![Screenshot (624)](https://user-images.githubusercontent.com/44056349/132171204-ab3aaffc-15ae-423f-aa06-e49f1420b931.png)

**Comment by VasudevJaiswal** [comment]
Join the org plz check your email or [org github page](https://github.com/jaidevstudio)

**Comment by CodingSpecies** [comment]
You can also show that you are part of this org, by making yourself public. This will show our profile org on your profile:
## Follow This:
1. After you join the organisation, search your name in the list of people. 🔍 
2.  Follow this below: ⬇️ 
![image](https://user-images.githubusercontent.com/70807500/130362669-7eb8ac9f-41e3-489e-b88b-1fe180e18129.png)
