### ISSUE TITLE
add akshita

### ISSUE THREAD

**Issue by akshitagupta15june** [Jaidevstudio/Unique-Github-Profiles#23]
![image](https://user-images.githubusercontent.com/57909583/132530399-dc60f648-e173-419a-ab33-ffd0aae1beaf.png)

**Comment by akshitagupta15june** [comment]
@AvidCoder101

**Comment by AvidCoder101** [comment]
@akshitagupta15june thanks (:

**Comment by AvidCoder101** [comment]
In data.json add your own object to the end of the file, your entry should be similar to this example:

 {
    "name": "Vasudev Jaiswal",
    "githubUsername": "VasudevJaiswal",
    "imageUrl": "https://user-images.githubusercontent.com/85981735/129255772-5bac726e-d98e-4eb4-8c9f-c2206b72c976.png",
    "issueNumber": 1
  }

**Comment by akshitagupta15june** [comment]
i have added check pull request

**Comment by AvidCoder101** [comment]
@akshitagupta15june sorry didn't spot that 😅! Thanks for contributing (:

**Comment by AvidCoder101** [comment]
You may close this issue now

**Comment by VasudevJaiswal** [comment]
@akshitagupta15june
Thank you for contributing
