### ISSUE TITLE
@codingspecies Plz imporve bugs

### ISSUE THREAD

**Issue by VasudevJaiswal** [Jaidevstudio/Unique-Github-Profiles#25]
@CodingSpecies 
All Porfiles Look Blur 

![Screenshot (109)](https://user-images.githubusercontent.com/85981735/132543986-6715c047-abef-413a-bdaf-c5fc4620e680.png)

**Comment by Panquesito7** [comment]
I think that's due to the quality of the image. There's not much we can do unless you take a better screenshot.

**Comment by CodingSpecies** [comment]
Yes I agree, it is because its only a screenshot, and how it has been uploaded, reducing the quality.

**Comment by VasudevJaiswal** [comment]
Ok Thank you
