### ISSUE TITLE
Alenjojo

### ISSUE THREAD

**Issue by Alenjojo** [Jaidevstudio/Unique-Github-Profiles#36]
![Capture](https://user-images.githubusercontent.com/51394913/133300175-55e3898e-59c4-46e4-b6fb-29c4ceb70ac2.PNG)

**Comment by CodingSpecies** [comment]
If you need anything- *help* or *support* - please reopen this issue, people will still be able to see your profile, even if it is closed. Thank you.

**Comment by Alenjojo** [comment]
sure, tq so much
